name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test-spa-pkce-backend:
    name: "Test: spa-pkce backend"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test --workspace=spa-pkce/apps/backend

  test-spa-pkce-frontend:
    name: "Test: spa-pkce frontend"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test --workspace=spa-pkce/apps/frontend

  build-spa-pkce-frontend:
    name: "Build: spa-pkce frontend"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --workspace=spa-pkce/apps/frontend
